default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: microposts_development

test:
  <<: *default
  database: microposts_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: microposts_production
  username: microposts
  password: <%= ENV['MICROPOSTS_DATABASE_PASSWORD'] %>
